// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/sample/hello.proto

//go:build protoopaque

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_sample_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Hello) SetName(v string) {
	x.xxx_hidden_Name = v
}

type Hello_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 Hello_builder) Build() *Hello {
	m0 := &Hello{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

var File_proto_sample_hello_proto protoreflect.FileDescriptor

const file_proto_sample_hello_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sample/hello.proto\x1a!google/protobuf/go_features.proto\"\"\n" +
	"\x05Hello\x12\x19\n" +
	"\x04name\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04nameB<Z2github.com/achtarudin/grpc-cutbray/protogen/sample\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_proto_sample_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_sample_hello_proto_goTypes = []any{
	(*Hello)(nil), // 0: Hello
}
var file_proto_sample_hello_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sample_hello_proto_init() }
func file_proto_sample_hello_proto_init() {
	if File_proto_sample_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sample_hello_proto_rawDesc), len(file_proto_sample_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sample_hello_proto_goTypes,
		DependencyIndexes: file_proto_sample_hello_proto_depIdxs,
		MessageInfos:      file_proto_sample_hello_proto_msgTypes,
	}.Build()
	File_proto_sample_hello_proto = out.File
	file_proto_sample_hello_proto_goTypes = nil
	file_proto_sample_hello_proto_depIdxs = nil
}
