name: PR Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Check out code

      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.24.0'
      
      - name: Check Go version
        run: go version

      - name: Cache go modules
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            $HOME/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Install Go Protobuf Plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "32"

      - name: Check protoc version
        run: protoc --version

      - name: Build protoc
        run: make protos
