name: PR Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v6
        with:
          go-version: '^1.24.0'
          check-latest: false
          cache: true
      
      - name: Check Go version
        run: go version

      - name: Cache go modules
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            $HOME/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Install Go Protobuf Plugins
        run: |
          apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      
      - name: Check protoc version
        run: protoc --version

      - name: Build protoc
        run: | 
          make clean
          make protos

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: 'protogen/*'
          commit_message: "ci(proto): auto-generate protobuf files skipping CI [skip ci]"

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch

      - name: Get the created tag
        run: "echo Tag Version: ${{ steps.tag_version.outputs.new_tag }}"

