name: PR Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v6
        with:
          go-version: '^1.24.0'
          cache: true
      
      - name: Check Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "32"

      - name: Check protoc version
        run: protoc --version
        
      - name: Install Go Protobuf Plugins
        shell: bash
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      
      - name: Build protoc
        shell: bash
        run: | 
          make clean
          make protos

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: 'protogen/*'
          commit_message: "ci(proto): auto-generate protobuf files skipping CI [skip ci]"

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch

      - name: Get the created tag
        run: "echo Tag Version: ${{ steps.tag_version.outputs.new_tag }}"

